// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjffloglkhjctwbrlyvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZmZsb2dsa2hqY3R3YnJseXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTMxMzEsImV4cCI6MjA1OTc2OTEzMX0.8BtGbFrS_bNV0UD3sjFl-1KMtgwVshRxUlGO-xipL80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);